ci: align PirateCash build infrastructure

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,20 +2,19 @@
 # - sudo/dist/group are set so as to get Blue Box VMs, necessary for [loopback]
 #   IPv6 support
 
-version: ~> 1.0
-
-dist: bionic
+sudo: required
+dist: trusty
 
 os: linux
 language: minimal
-arch: amd64
 
 services:
   - docker
 
 cache:
+  ccache: true
   directories:
-    - $BASE_BUILD_DIR/releases/$HOST
+    - $HOME/cache
 env:
   global:
     # DOCKER_HUB_USER
@@ -33,20 +32,20 @@ stages:
 builddepends: &builddepends
   stage: build depends
   script:
-    - $DOCKER_RUN_IN_BUILDER ./ci/dash/build_depends.sh
+    - $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh
 
 buildsrc: &buildsrc
   stage: build src
   script:
-    - $DOCKER_RUN_IN_BUILDER ./ci/dash/build_depends.sh
-    - $DOCKER_RUN_IN_BUILDER ./ci/dash/build_src.sh
+    - $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh
+    - $DOCKER_RUN_IN_BUILDER ./ci/build_src.sh
 
 runtests: &runtests
   stage: run tests
   script:
-    - $DOCKER_RUN_IN_BUILDER ./ci/dash/build_depends.sh
-    - $DOCKER_RUN_IN_BUILDER ./ci/dash/build_src.sh
-    - $DOCKER_RUN_IN_BUILDER ./ci/dash/test_unittests.sh
+    - $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh
+    - $DOCKER_RUN_IN_BUILDER ./ci/build_src.sh
+    - $DOCKER_RUN_IN_BUILDER ./ci/test_unittests.sh
     - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then extended="--extended --exclude feature_pruning,feature_dbcrash"; fi
     - $DOCKER_RUN_IN_BUILDER ./ci/test_integrationtests.sh --quiet --jobs=3 ${extended}
 
@@ -54,91 +53,91 @@ builddocker: &builddocker
   stage: build docker
   script:
     # no need to run tests again here
-    - if [ "$DOCKER_BUILD" = "true" ]; then $DOCKER_RUN_IN_BUILDER ./ci/dash/build_depends.sh && $DOCKER_RUN_IN_BUILDER ./ci/dash/build_src.sh && BUILD_DIR=build-ci/dashcore-$BUILD_TARGET ./ci/dash/build-docker.sh; fi
-    - CI_RETRY_EXE="travis_retry"
-    - CACHE_ERR_MSG="Error! Initial build successful, but not enough time remains to run later build stages and tests. See https://docs.travis-ci.com/user/customizing-the-build#build-timeouts . Please manually re-run this job by using the travis restart button. The next run should not time out because the build cache has been saved."
+    - if [ "$DOCKER_BUILD" = "true" ]; then $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh && $DOCKER_RUN_IN_BUILDER ./ci/build_src.sh && BUILD_DIR=build-ci/piratecashcore-$BUILD_TARGET ./docker/build-docker.sh; fi
+
+    - MAKEJOBS=-j3
+    - RUN_UNIT_TESTS=true
+    - RUN_FUNCTIONAL_TESTS=true
+    - RUN_BENCH=false  # Set to true for any one job that has debug enabled, to quickly check bench is not crashing or hitting assertions
+    - RUN_FUZZ_TESTS=false
+    - DOCKER_NAME_TAG=ubuntu:18.04
+    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
+    - CCACHE_SIZE=100M
+    - CCACHE_TEMPDIR=/tmp/.ccache-temp
+    - CCACHE_COMPRESS=1
+    - CCACHE_DIR=$HOME/.ccache
+    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
+    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
+    - WINEDEBUG=fixme-all
+    - DOCKER_PACKAGES="build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git ca-certificates ccache"
 before_install:
-  - set -o errexit; source ./ci/test/00_setup_env.sh
-  - set -o errexit; source ./ci/test/03_before_install.sh
+  - set -o errexit; source .travis/test_03_before_install.sh
 install:
-  - set -o errexit; source ./ci/test/04_install.sh
+  - set -o errexit; source .travis/test_04_install.sh
 before_script:
-  # Temporary workaround for https://github.com/bitcoin/bitcoin/issues/16368
-  - for i in {1..4}; do echo "$(sleep 500)" ; done &
-  - set -o errexit; source ./ci/test/05_before_script.sh &> "/dev/null"
+  - set -o errexit; source .travis/test_05_before_script.sh
 script:
-  - if [[ $SECONDS -gt 1200 ]]; then set +o errexit; echo "Travis early exit to cache current state"; false; else set -o errexit; source .travis/test_06_script.sh; fi
+  - if [ $SECONDS -gt 1200 ]; then set +o errexit; echo "Travis early exit to cache current state"; false; else set -o errexit; source .travis/test_06_script.sh; fi
 after_script:
   - echo $TRAVIS_COMMIT_RANGE
+  - echo $TRAVIS_COMMIT_LOG
 jobs:
   include:
     # build depends
     - <<: *builddepends
-      name: depends-arm-linux
       env: BUILD_TARGET=arm-linux
     - <<: *builddepends
       name: depends-win64
       env: BUILD_TARGET=win64
     - <<: *builddepends
-      name: depends-linux64
+      env: BUILD_TARGET=linux32
+    - <<: *builddepends
       env: BUILD_TARGET=linux64
     - <<: *builddepends
-      name: depends-linux64_nowallet
       env: BUILD_TARGET=linux64_nowallet
     - <<: *builddepends
-      name: depends-linux64_release
-      env:
-        - BUILD_TARGET=linux64_release
-        - DOCKER_BUILD=true
+      env: BUILD_TARGET=linux64_release DOCKER_BUILD=true
     - <<: *builddepends
-      name: depends-mac
       env: BUILD_TARGET=mac
     # build source
     - <<: *buildsrc
-      name: src-arm-linux
       env: BUILD_TARGET=arm-linux
     - <<: *buildsrc
       name: src-win64
       env: BUILD_TARGET=win64
     - <<: *buildsrc
-      name: src-linux64
+      env: BUILD_TARGET=linux32
+    - <<: *buildsrc
       env: BUILD_TARGET=linux64
     - <<: *buildsrc
-      name: src-linux64_nowallet
       env: BUILD_TARGET=linux64_nowallet
     - <<: *buildsrc
-      name: src-linux64_release
-      env:
-        - BUILD_TARGET=linux64_release
-        - DOCKER_BUILD=true
+      env: BUILD_TARGET=linux64_release DOCKER_BUILD=true
     - <<: *buildsrc
-      name: src-mac
       env: BUILD_TARGET=mac
     # run tests (no tests for arm-linux and mac)
     - <<: *runtests
       name: tests-win64
       env: BUILD_TARGET=win64
     - <<: *runtests
-      name: tests-linux64
+      env: BUILD_TARGET=linux32
+    - <<: *runtests
       env: BUILD_TARGET=linux64
     - <<: *runtests
-      name: tests-linux64_nowallet
       env: BUILD_TARGET=linux64_nowallet
     - <<: *runtests
-      name: tests-linux64_release
-      env:
-        - BUILD_TARGET=linux64_release
-        - DOCKER_BUILD=true
+      env: BUILD_TARGET=linux64_release DOCKER_BUILD=true
     # build docker
     - <<: *builddocker
-      name: docker-linux64_release
-      env:
-        - BUILD_TARGET=linux64_release
-        - DOCKER_BUILD=true
+      env: BUILD_TARGET=linux64_release DOCKER_BUILD=true
 
 before_cache:
   # Save builder image
-  - docker save dash-builder-$BUILD_TARGET-$TRAVIS_JOB_NUMBER $(docker history -q dash-builder-$BUILD_TARGET-$TRAVIS_JOB_NUMBER | grep -v \<missing\>) | gzip -2 > $HOME/cache/docker/dash-builder-$BUILD_TARGET.tar.gz
+  - docker save piratecash-builder-$BUILD_TARGET-$TRAVIS_JOB_NUMBER $(docker history -q piratecash-builder-$BUILD_TARGET-$TRAVIS_JOB_NUMBER | grep -v \<missing\>) | gzip -2 > $HOME/cache/docker/piratecash-builder-$BUILD_TARGET.tar.gz
+
+before_install:
+  - travis_retry travis_apt_get_update
+  - travis_retry sudo apt-get -yq --no-install-suggests --no-install-recommends install docker-ce realpath
 
 install:
     # Fix annoying Travis bug: a branch with a single commit has an empty TRAVIS_COMMIT_RANGE sometimes
@@ -147,7 +146,7 @@ install:
     - export PULL_REQUEST="$TRAVIS_PULL_REQUEST"
     - export COMMIT_RANGE="$TRAVIS_COMMIT_RANGE"
     - export JOB_NUMBER="$TRAVIS_JOB_NUMBER"
-    - export HOST_SRC_DIR=$BASE_BUILD_DIR
+    - export HOST_SRC_DIR=$TRAVIS_BUILD_DIR
     - export HOST_CACHE_DIR=$HOME/cache
     - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
     - source ./ci/matrix.sh
@@ -155,37 +154,149 @@ install:
     # Keep this as it makes caching related debugging easier
     - ls -lah $HOST_CACHE_DIR && ls -lah $HOST_CACHE_DIR/depends && ls -lah $HOST_CACHE_DIR/ccache && ls -lah $HOST_CACHE_DIR/docker
     # Load cached builder image
-    - if [ -f $HOST_CACHE_DIR/docker/dash-builder-$BUILD_TARGET.tar.gz ]; then zcat $HOST_CACHE_DIR/docker/dash-builder-$BUILD_TARGET.tar.gz | docker load || true; fi
-    - travis_retry docker pull ubuntu:focal
+    - if [ -f $HOST_CACHE_DIR/docker/piratecash-builder-$BUILD_TARGET.tar.gz ]; then zcat $HOST_CACHE_DIR/docker/piratecash-builder-$BUILD_TARGET.tar.gz | docker load || true; fi
+    - travis_retry docker pull ubuntu:bionic
     - travis_retry docker build -t $BUILDER_IMAGE_NAME --build-arg=USER_ID=$UID --build-arg=GROUP_ID=$UID --build-arg=BUILD_TARGET=$BUILD_TARGET -f contrib/containers/ci/Dockerfile ci
 before_script:
     # Make sure stdout is in blocking mode. Otherwise builds will fail due to large writes to stdout
     # See https://github.com/travis-ci/travis-ci/issues/4704. If this gets fixed, this line can also be removed.
     - python3 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
     # Build docker image only for develop branch of the main repo
-    - if [ "$TRAVIS_REPO_SLUG" != "dashpay/dash" -o "$TRAVIS_BRANCH" != "develop" -o "$TRAVIS_PULL_REQUEST" != "false" ]; then export DOCKER_BUILD="false"; echo DOCKER_BUILD=$DOCKER_BUILD; fi
-    # TODO(ignore if don't use travis): Check keys and signed commits
-    #- if [ "$TRAVIS_REPO_SLUG" = "dashpay/dash" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then travis_retry gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys $(<contrib/verify-commits/trusted-keys); fi
-    #- if [ "$TRAVIS_REPO_SLUG" = "dashpay/dash" -a "$TRAVIS_EVENT_TYPE" = "cron" ]; then travis_wait 30 contrib/verify-commits/verify-commits.py; fi
+    - if [ "$TRAVIS_REPO_SLUG" != "piratecash/piratecash" -o "$TRAVIS_BRANCH" != "develop" -o "$TRAVIS_PULL_REQUEST" != "false" ]; then export DOCKER_BUILD="false"; echo DOCKER_BUILD=$DOCKER_BUILD; fi
+    # TODO: Check keys and signed commits
+    #- if [ "$TRAVIS_REPO_SLUG" = "piratecash/piratecash" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then while read LINE; do travis_retry gpg --keyserver hkp://subset.pool.sks-keyservers.net --recv-keys $LINE; done < contrib/verify-commits/trusted-keys; fi
+    #- if [ "$TRAVIS_REPO_SLUG" = "piratecash/piratecash" -a "$TRAVIS_EVENT_TYPE" = "cron" ]; then travis_wait 30 contrib/verify-commits/verify-commits.py; fi
 after_script:
     - echo $TRAVIS_COMMIT_RANGE
     - echo $TRAVIS_COMMIT_LOG
 after_success:
-    - if [ "$DOCKER_BUILD" = "true" ]; then docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD && ./ci/dash/push-docker.sh; fi
+    - if [ "$DOCKER_BUILD" = "true" ]; then docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD && ./docker/push-docker.sh; fi
     - stage: lint
       name: 'lint'
       env:
-      cache: pip
+      sudo: false
+      cache: false
       language: python
-      python: '3.8' # Oldest supported version according to doc/dependencies.md
+      python: '3.5' # Oldest supported version according to doc/dependencies.md
       install:
-        - set -o errexit; source ./ci/lint/04_install.sh
+        - set -o errexit; source .travis/lint_04_install.sh
       before_script:
-        - set -o errexit; source ./ci/lint/05_before_script.sh
+        - set -o errexit; source .travis/lint_05_before_script.sh
       script:
-        - set -o errexit; source ./ci/lint/06_script.sh
+        - set -o errexit; source .travis/lint_06_script.sh
+
+    - stage: extended-lint
+      name: 'extended lint [runtime >= 60 seconds]'
+      env:
+      cache: false
+      language: python
+      python: '3.5'
+      install:
+        - set -o errexit; source .travis/extended_lint_04_install.sh
+      before_script:
+        - set -o errexit; source .travis/lint_05_before_script.sh
+      script:
+        - set -o errexit; source .travis/extended_lint_06_script.sh
 
     - stage: test
-      name: 'x86_64 Linux  [GOAL: install]  [focal]  [no wallet]'
+      name: 'ARM  [GOAL: install]  [no unit or functional tests]'
       env: >-
-        FILE_ENV="./ci/test/00_setup_env_native_nowallet.sh"
+        HOST=arm-linux-gnueabihf
+        PACKAGES="python3 g++-arm-linux-gnueabihf"
+        RUN_UNIT_TESTS=false
+        RUN_FUNCTIONAL_TESTS=false
+        GOAL="install"
+        BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
+    - stage: test
+      name: 'Win64  [GOAL: deploy]  [no gui tests]'
+      env: >-
+        HOST=x86_64-w64-mingw32
+        PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine-binfmt wine64"
+        RUN_FUNCTIONAL_TESTS=false
+        GOAL="deploy"
+        BITCOIN_CONFIG="--enable-reduce-exports --disable-gui-tests"
+
+    - stage: test
+      name: '32-bit + dash  [GOAL: install]'
+      env: >-
+        HOST=i686-pc-linux-gnu
+        PACKAGES="g++-multilib python3-zmq"
+        GOAL="install"
+        BITCOIN_CONFIG="--enable-zmq --with-gui=qt5 --disable-bip70 --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++"
+        CONFIG_SHELL="/bin/dash"
+
+    - stage: test
+      name: 'x86_64 Linux  [GOAL: install]  [bionic]  [uses qt5 dev package instead of depends Qt to speed up build and avoid timeout]'
+      env: >-
+        HOST=x86_64-unknown-linux-gnu
+        PACKAGES="python3-zmq qtbase5-dev qttools5-dev-tools protobuf-compiler libdbus-1-dev libharfbuzz-dev libprotobuf-dev"
+        DEP_OPTS="NO_QT=1 NO_UPNP=1 DEBUG=1 ALLOW_HOST_PACKAGES=1"
+        TEST_RUNNER_EXTRA="--coverage --extended --exclude feature_dbcrash"  # Run extended tests so that coverage does not fail, but exclude the very slow dbcrash
+        GOAL="install"
+        BITCOIN_CONFIG="--enable-zmq --with-gui=qt5 --enable-glibc-back-compat --enable-reduce-exports --enable-debug CFLAGS=\"-g0 -O2 -funsigned-char\" CXXFLAGS=\"-g0 -O2 -funsigned-char\""
+
+    - stage: test
+      name: 'x86_64 Linux  [GOAL: install]  [trusty]  [no functional tests, no depends, only system libs]'
+      env: >-
+        FILE_ENV="./ci/test/00_setup_env_amd64_trusty.sh"
+
+    - stage: test
+      name: 'x86_64 Linux  [GOAL: install]  [xenial]  [no depends, only system libs, sanitizers: thread (TSan), no wallet]'
+      env: >-
+        HOST=x86_64-unknown-linux-gnu
+        DOCKER_NAME_TAG=ubuntu:16.04
+        PACKAGES="python3-zmq qtbase5-dev qttools5-dev-tools libssl-dev libevent-dev bsdmainutils libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev libdb5.3++-dev libminiupnpc-dev libzmq3-dev libprotobuf-dev protobuf-compiler libqrencode-dev"
+        NO_DEPENDS=1
+        GOAL="install"
+        BITCOIN_CONFIG="--enable-zmq --with-incompatible-bdb --enable-glibc-back-compat --enable-reduce-exports --with-gui=qt5 CPPFLAGS=-DDEBUG_LOCKORDER"
+# x86_64 Linux (no depends, only system libs)
+    - stage: test
+      name: 'x86_64 Linux  [GOAL: install]  [xenial]  [no depends, only system libs, sanitizers: thread (TSan), no wallet]'
+      env: >-
+        HOST=x86_64-unknown-linux-gnu
+        DOCKER_NAME_TAG=ubuntu:16.04
+        PACKAGES="clang llvm python3-zmq qtbase5-dev qttools5-dev-tools libssl-dev libevent-dev bsdmainutils libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev libdb5.3++-dev libminiupnpc-dev libzmq3-dev libprotobuf-dev protobuf-compiler libqrencode-dev"
+        NO_DEPENDS=1
+        RUN_FUNCTIONAL_TESTS=false # Disabled for now. TODO identify suppressions or exclude specific tests
+        GOAL="install"
+        BITCOIN_CONFIG="--enable-zmq --with-incompatible-bdb --with-gui=qt5 CPPFLAGS=-DDEBUG_LOCKORDER --with-sanitizers=thread --disable-hardening --disable-asm CC=clang CXX=clang++"
+    - stage: test
+      name: 'x86_64 Linux  [GOAL: install]  [bionic]  [no depends, only system libs, sanitizers: address/leak (ASan + LSan) + undefined (UBSan) + integer]'
+      env: >-
+        HOST=x86_64-unknown-linux-gnu
+        PACKAGES="clang llvm python3-zmq qtbase5-dev qttools5-dev-tools libssl1.0-dev libevent-dev bsdmainutils libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev libdb5.3++-dev libminiupnpc-dev libzmq3-dev libprotobuf-dev protobuf-compiler libqrencode-dev"
+        NO_DEPENDS=1
+        RUN_BENCH=true
+        GOAL="install"
+        BITCOIN_CONFIG="--enable-zmq --with-incompatible-bdb --with-gui=qt5 CPPFLAGS=-DDEBUG_LOCKORDER --with-sanitizers=integer,undefined CC=clang CXX=clang++"
+    - stage: test
+      name: 'x86_64 Linux  [GOAL: install]  [bionic]  [no wallet]'
+      env: >-
+        HOST=x86_64-unknown-linux-gnu
+        PACKAGES="clang llvm python3 libssl1.0-dev libevent-dev bsdmainutils libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev"
+        NO_DEPENDS=1
+        RUN_UNIT_TESTS=false
+        RUN_FUNCTIONAL_TESTS=false
+        RUN_FUZZ_TESTS=true
+        GOAL="install"
+        BITCOIN_CONFIG="--enable-fuzz --with-sanitizers=fuzzer,address CC=clang CXX=clang++"
+
+    - stage: test
+      env: >-
+        HOST=x86_64-unknown-linux-gnu
+        PACKAGES="python3-zmq"
+        DEP_OPTS="NO_WALLET=1"
+        GOAL="install"
+        BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
+
+    - stage: test
+      name: 'macOS 10.12  [GOAL: deploy] [no functional tests]'
+      env: >-
+        HOST=x86_64-apple-darwin19
+        PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python3-dev python3-setuptools"
+        export XCODE_VERSION=11.3.1
+        export XCODE_BUILD_ID=11C505
+        RUN_UNIT_TESTS=false
+        RUN_FUNCTIONAL_TESTS=false
+        GOAL="deploy"
+        BITCOIN_CONFIG="--enable-gui --enable-reduce-exports --enable-werror"
